import type { Metadata } from "next";
import "./globals.css";
import Toaster from "./components/toaster";
import { Rubik } from "next/font/google";

const outfit = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
      <body  className={outfit.variable}>
        {children}

        <Toaster />
      </body>
    </html>
  );
}
